const user = {
  username: "surajverma2587",
  id: 10376859,
  profileImageUrl: "https://avatars.githubusercontent.com/u/10376859?v=4",
  profileUrl: "https://github.com/surajverma2587",
  followers: [
    {
      username: "AkenEagle",
      id: 19980311,
      profileImageUrl: "https://avatars.githubusercontent.com/u/19980311?v=4",
      profileUrl: "https://github.com/AkenEagle",
      followers: [],
      repos: [],
    },
    {
      username: "AkenEagle",
      id: 19980311,
      profileImageUrl: "https://avatars.githubusercontent.com/u/19980311?v=4",
      profileUrl: "https://github.com/AkenEagle",
      followers: [],
      repos: [],
    },
    {
      username: "AkenEagle",
      id: 19980311,
      profileImageUrl: "https://avatars.githubusercontent.com/u/19980311?v=4",
      profileUrl: "https://github.com/AkenEagle",
      followers: [],
      repos: [],
    },
  ],
  following: [
    {
      username: "AkenEagle",
      id: 19980311,
      profileImageUrl: "https://avatars.githubusercontent.com/u/19980311?v=4",
      profileUrl: "https://github.com/AkenEagle",
      followers: [],
      repos: [],
    },
    {
      username: "AkenEagle",
      id: 19980311,
      profileImageUrl: "https://avatars.githubusercontent.com/u/19980311?v=4",
      profileUrl: "https://github.com/AkenEagle",
      followers: [],
      repos: [],
    },
    {
      username: "AkenEagle",
      id: 19980311,
      profileImageUrl: "https://avatars.githubusercontent.com/u/19980311?v=4",
      profileUrl: "https://github.com/AkenEagle",
      followers: [],
      repos: [],
    },
  ],
  repos: [
    {
      id: 430829236,
      name: "avengers-cli",
      private: false,
      owner: {
        username: "AkenEagle",
        id: 19980311,
        profileImageUrl: "https://avatars.githubusercontent.com/u/19980311?v=4",
        profileUrl: "https://github.com/AkenEagle",
        followers: [],
        repos: [],
      },
      profileUrl: "https://github.com/surajverma2587/avengers-cli",
      description: null,
      createdAt: "2021-11-22T18:54:03Z",
      updatedAt: "2021-11-22T20:41:43Z",
      pushedAt: "2021-11-22T20:41:40Z",
      language: "JavaScript",
      openIssuesCount: 0,
      license: null,
    },
    {
      id: 430829236,
      name: "avengers-cli",
      private: false,
      owner: {
        username: "AkenEagle",
        id: 19980311,
        profileImageUrl: "https://avatars.githubusercontent.com/u/19980311?v=4",
        profileUrl: "https://github.com/AkenEagle",
        followers: [],
        repos: [],
      },
      profileUrl: "https://github.com/surajverma2587/avengers-cli",
      description: null,
      createdAt: "2021-11-22T18:54:03Z",
      updatedAt: "2021-11-22T20:41:43Z",
      pushedAt: "2021-11-22T20:41:40Z",
      language: "JavaScript",
      openIssuesCount: 0,
      license: null,
    },
  ],
  name: "Suraj Verma",
  company: "Booking.com",
  blog: "",
  location: " Manchester, UK",
  email: null,
  bio: "Senior Software Engineer and Full Stack Instructor passionate about transforming people in to seasoned software engineers.",
  twitter_username: null,
  numberOfPublicRepos: 122,
  numberOfFollowers: 50,
  numberOfFollowing: 8,
  createdAt: "2015-01-03T00:32:06Z",
  updatedAt: "2022-01-26T09:58:50Z",
};
